### ISSUE TITLE
Publishing go-live checklist (batch-1)

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#238]
Must-haves:
- [x] Handle redirects from old theblog URLs #198 
- [x] Correct URLs in nav #240 (Mon 6/22)
- [x] Load testing (10x MAX 2019) #148 (Mon 6/22)
- [x] Initial design implementation #179 (Thu 6/23)
- [x] Pentesting #237 (Tue 6/23)
- [x] Move imported articles to /en/publish #232 (Wed 6/24)
- [x] Allow crawlers #173 (Wed 6/24)
- [x] Eng Go (Wed 6/24)
- [x] Analytics Go #311 (Tue 8/4)
- [x] New CMP #247 (Thu 8/6)
- [x] Eurovision Go (8/10)
- [x] Design Go (8/10)
- [x] Accessibility Go (8/10)
- [x] QA Go (8/10) 
- [x] PM Go (8/10)
- [x] Biz Go (8/10)
- [x] DNS switch #245 & CritSit room (Wed 8/12)

**Comment by avanishgandhi** [comment]
@rofe we should add the following to your checklist
- Accessibility testing (there will be some stories which we will get from that team which we will need to develop solution for)
- SEO final review of end product (to make sure that we have tagged the content correctly with keywords and such so we are at parity on our ranking for articles) 
- UAT - 1 week? (we need Matt and Giselle to UAT the new pages and make sure that new navigation + IA makes sense with the migrated content)

**Comment by rofe** [comment]
Thanks @avanishgandhi 

> * Accessibility testing (there will be some stories which we will get from that team which we will need to develop solution for)

I have added a separate Go step for accessibility above

> * SEO final review of end product (to make sure that we have tagged the content correctly with keywords and such so we are at parity on our ranking for articles)

Can we wrap this into the QA Go step?

> * UAT - 1 week? (we need Matt and Giselle to UAT the new pages and make sure that new navigation + IA makes sense with the migrated content)

Yes, this was the intention of the Biz Go step

**Comment by rofe** [comment]
@avanishgandhi re: _Design GO_ can you organize the design review on http://theblog-adobe.hlx.page? I would simply create GH issues with a _Design_ label, and then prioritize them into 2 categories: actual go-live blockers and incremental improvements.

**Comment by rofe** [comment]
I just noticed that @narcis-radu updated the due date for #247 from 7/23 to 8/6 - I guess this also means that the go-live cannot happen before?

**Comment by rofe** [comment]
Moved DNS switch date to Wed 8/12

**Comment by sgliatto** [comment]
@rofe Please add Analytics "go" to the go-live checklist. Corresponding git https://github.com/adobe/theblog/issues/311

**Comment by narcis-radu** [comment]
It's a "go" from Eurovision. @avanishgandhi has removed the Search icon from the navigation

**Comment by rofe** [comment]
https://blog.adobe.com went live on Wed August 12 at around ~1:15PM UTC 🎉
