### ISSUE TITLE
implement popular stories 

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/theblog#88]
implement popular stories 

- [ ] https://github.com/adobe/helix-run-query/blob/master/src/queries/top-blogposts.sql needs the ability to filter by URL prefix, so that only posts with `https://theblog.helix-demo.xyz/ms` get listed
- [ ] modify the query so that `top-blogposts` also includes a link to the `helix-index-pipelines` URL for metadata extraction https://github.com/adobe/helix-run-query/issues/101
- [ ] in https://github.com/davidnuescheler/theblog/blob/master/scripts.js modify the `setupHomepage` function so that it will also request the `top-blogposts` query
- [ ] for each top blogpost, retrieve the metadata from `helix-index-pipelines`
- [ ] for each top blogpost, create a div and link with title, description, thumbnail and links

after that, we will have a (slow) implementation of the top pages, with excessive execution of `helix-index-pipelines`, so in order to improve performance, also

- [ ] add the Helix Vulcain filters to `helix-run-query` https://github.com/adobe/helix-run-query/issues/101
- [ ] make sure that the Helix Run Query execution is routed through Fastly (e.g. with https://github.com/adobe/helix-home/issues/95) so that the Vulcain-powered HTTP server-push is executed
- [ ] make sure that Helix Index Pipelines execution is also routed through Fastly, for the same reason. This requires changes to https://github.com/adobe/helix-pages/blob/master/vcl/extensions.vcl

After that, a request to Helix Run Query will also server-push the metadata for each top blog post.

**Comment by rofe** [comment]
Note that as long as we devs are the only ones surfing the Helix site, and we will be for quite a while, the result of such a query will likely be... unusable :)

I would defer this for later, it doesn't show up in the top priorities defined by the PO.

**Comment by rofe** [comment]
This feature is no longer part of the new design.
